name: CI
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sast_scan_job:
    runs-on: ubuntu-lates
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . 

    
